---

- hosts: all

  tasks:
    - name: install needed tools
      apt: pkg={{item}}
      with_items:
        - python-software-properties
        - wget

    - name: download obm.org gpg key
      action: command /usr/bin/wget -q  http://deb.obm.org/obmgpg.pub

    - name: install obm.org key
      action: command /usr/bin/apt-key add obmgpg.pub

    - name: add obm repository
      apt_repository: repo='deb http://deb.obm.org/30/next obm obm' state=present
    - name: remove exim
      action: command /usr/bin/apt-get remove -y exim4 exim4-config

    - name: copy preseeds for obm install
      copy: src=debconf dest=/tmp/debconf

    - name: import preseeds values
      action: command debconf-set-selections /tmp/debconf

    - name: install obm
      action: command /usr/bin/apt-get install -y obm obm-sync


